name: Reusable Badge Update

on:
  workflow_call:
    inputs:
      reason:
        required: false
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  update-badges:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r deaditude/requirements.txt

      - name: Generate badges for updated technologies
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          cd deaditude && python -m scripts.generate_badges

      - name: Create Pull Request for README update
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update technology badges [skip ci]"
          branch: "auto/update-badges-${{ github.run_id }}"
          title: "Automated update of technology badges"
          body: "This PR was created automatically by GitHub Actions."
          base: main
          delete-branch: true
          add-paths: README.md
          draft: false